### PR TITLE
Add custom images to the footer of the papers within mechthesis

### PR DESCRIPTION
**Pull request by Simkern**
I wanted to have videos in the papers my thesis and added them as custom images in the footers of the papers.

Several colleagues have asked for the code so I thought I might as well add it to the repo. It's not extremely elegant but gets the job done.

The changes include an alternative definition of the footers for the papers in the MechThesis.cls file and the definition of two custom commands for the insertion and sizing of the images themselves, which I have put in the command.tex file. 

In the current pull request, I have commented out the original footers. If the required images are missing in the compile folder, the document will compile and show the images in draft mode on the corresponding pages together with the warnings/errors.

### CODE REVIEW

**Comment by Simkern** [comment]
Here is an example of the output for paper 1 using pictures named:

movie_p1_0.png   % the shift by (-1) is due to the fact that the page counter is upgraded (to 1) after \putimg is called.
movie_p1_3.png
movie_p1_5.png ...

[putimg_example.pdf](https://github.com/eX-Mech/mechthesis/files/12410062/putimg_example.pdf)

**Comment by ashwinvis** [comment]
@Simkern can you add it to the overview / one of the paper, so others would know how to use it?

**Comment by Simkern** [comment]
No problem, I added a silly example to the template papers and an note in the README.md indicating where to disable the feature. The figures are added within the imgs folder for now.

**Comment by ashwinvis** [comment]
Very cool. Now I should get hold of your thesis to see how this looks.

**Comment by Simkern** [comment]
Awesome! Well I'm still in Stockholm for another month, so you are welcome to come visit at KTH and get one :)

**Pull request merged**
